name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install poetry
        run: pipx install poetry

